name: Build Android
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - precision: double
            arch: arm64
            platform: android
            target-type: template_debug
          - precision: double
            arch: x86_64
            platform: android
            target-type: template_debug
          - precision: double
            arch: arm64
            platform: android
            target-type: template_release
          - precision: double
            arch: x86_64
            platform: android
            target-type: template_release

    # Taken mostly from https://github.com/godotengine/godot-cpp-template/blob/main/.github/workflows/builds.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.platform }}
          em-version: 3.1.62

      # Build GDExtension (with caches)
      - name: Cache .scons_cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.scons-cache/
          key: ${{ matrix.platform }}_${{ matrix.arch }}_${{ matrix.precision }}_${{ matrix.target-type }}_cache

      - name: Build GDExtension
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons target=${{ matrix.target-type }} platform=${{ matrix.platform }} arch=${{ matrix.arch }} precision=${{ matrix.precision }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libutilityai-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.precision }}-${{ matrix.target-type }}
          path: ${{ github.workspace }}/demo/addons/utility_ai/bin/*.so
          if-no-files-found: error
